[project]
name = "paper-agent"
version = "0.1.0"
description = "AI based Paper Agent with multiple functions."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "pypdf>=6.0.0",
    "sentence-transformers>=5.1.0",
]
